# Generated by Django 4.2.7 on 2023-11-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_userbalance_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalance',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
