# Generated by Django 4.2.7 on 2023-11-27 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0003_userbalance_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbalance',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
