# Generated by Django 4.2.7 on 2023-11-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0004_rename_phone_number_userbalance_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbalance',
            name='phone',
        ),
    ]
